/*Copyright (c) 2017-2018 bluemix training*/

package com.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


public interface HrdbQueryExecutorService {


}


